//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLogs
    {
        public int LogID { get; set; }
        public string ExecuteCommand { get; set; }
        public Nullable<int> WorkHoursID { get; set; }
        public Nullable<int> OldEmployeeID { get; set; }
        public Nullable<System.DateTime> OldDate { get; set; }
        public string OldTask { get; set; }
        public string OldComment { get; set; }
        public Nullable<int> NewEmployeeID { get; set; }
        public Nullable<System.DateTime> NewDate { get; set; }
        public string NewTask { get; set; }
        public string NewComment { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
    }
}
