//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHours
    {
        public int WorkHoursID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Task { get; set; }
        public int LogHours { get; set; }
        public string Comment { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
